import io
import json
import math
from pathlib import Path
import subprocess
import tarfile
import tempfile
import unittest

from maintainability import (analyze, archive_files, distribution, report, scope,
                             halstead, maintainability_index, index_summary, comparison_details, index_interpretation)
try:
    import lizard
except ImportError:
    lizard = None


class MaintainabilityTests(unittest.TestCase):
    def test_scope(self):
        self.assertEqual(scope('inst/include/interface/Quadra/a.hpp', ''), ('C++', 'vendored'))
        self.assertEqual(scope('src/RcppExports.cpp', ''), ('C++', 'generated'))
        self.assertEqual(scope('R/generated.R', '# Generated by cpp11'), ('R', 'generated'))
        self.assertEqual(scope('tests/testthat/a.R', ''), ('R', 'tests-examples-other'))
        self.assertEqual(scope('src/quadra.cpp', ''), ('C++', 'owned'))
        self.assertEqual(scope('inst/include/interface/TMB/init_tmb.hpp', ''), ('C++', 'owned'))

    def test_distribution_and_archive(self):
        self.assertEqual(distribution(list(range(1, 21)))['p95'], 19)
        self.assertIsNone(distribution([])['median'])
        stream = io.BytesIO()
        with tarfile.open(fileobj=stream, mode='w:gz') as tar:
            info = tarfile.TarInfo('root/R/foo.R'); content = b'f <- function(x) x'
            info.size = len(content); tar.addfile(info, io.BytesIO(content))
        stream.seek(0)
        self.assertEqual(list(archive_files(stream)), [('R/foo.R', content.decode())])

    @unittest.skipIf(lizard is None, 'requires scripts/requirements-maintainability.txt')
    def test_metrics_and_multibranch_report(self):
        sources = [('R/f.R', 'f <- function(x) {\n if (x > 0) x else -x\n}'),
                   ('src/f.cpp', 'int f(int x) { if (x) return 1; return 0; }'),
                   ('inst/include/interface/Quadra/vendor.hpp', 'int vendor() {return 0;}')]
        result = analyze(sources)
        self.assertEqual(result['status'], 'measured')
        self.assertEqual(result['languages']['R']['function_count'], 1)
        self.assertEqual(result['languages']['C++']['complexity']['maximum'], 2)
        self.assertEqual(result['exclusions']['vendored'], 1)
        with tempfile.TemporaryDirectory() as directory:
            paths = []
            for ref in ('baseline', 'quadra', 'third'):
                path = Path(directory) / f'{ref}.json'
                path.write_text(json.dumps(dict(result, ref=ref, commit='a'*40)))
                paths.append(path)
            text = report(paths)
            self.assertIn('| third | R | measured', text)
            self.assertIn('not measured', text)
            self.assertIn('CCN median / p95 / max', text)

    @unittest.skipIf(lizard is None, 'requires scripts/requirements-maintainability.txt')
    def test_duplicate_tokens_and_empty_language(self):
        body = '\n'.join(f'if(x > {n}) x <- x + {n}' for n in range(30))
        result = analyze([('R/a.R', 'a <- function(x) {\n'+body+'\n}'),
                          ('R/b.R', 'b <- function(x) {\n'+body+'\n}')])
        self.assertGreater(result['languages']['R']['duplicate_token_percent'], 0)
        self.assertEqual(result['languages']['C++']['function_count'], 0)
        self.assertIsNone(result['languages']['C++']['duplicate_token_percent'])

    def test_index_formula_and_undefined_inputs(self):
        self.assertAlmostEqual(maintainability_index(math.e, 2, math.e), 149.14 * 100 / 171)
        self.assertEqual(maintainability_index(1e12, 1000, 10000), 0)
        self.assertIsNone(maintainability_index(0, 1, 10))
        self.assertIsNone(maintainability_index(10, 0, 0))
        base = maintainability_index(100, 2, 10)
        self.assertLess(maintainability_index(200, 2, 10), base)
        self.assertLess(maintainability_index(100, 3, 10), base)
        self.assertLess(maintainability_index(100, 2, 20), base)

    def test_index_aggregation_and_missing(self):
        summary = index_summary([dict(mi=10, nloc=90), dict(mi=90, nloc=10),
                                 dict(mi=None, nloc=5)])
        self.assertEqual(summary['nloc_weighted_mean'], 18)
        self.assertEqual(summary['file_mean'], 50)
        self.assertEqual(summary['nloc_below_20_percent'], 90)
        self.assertEqual(summary['p10'], 10)
        self.assertEqual(summary['measured_nloc'], 100)
        self.assertEqual(summary['total_nloc'], 105)
        self.assertIsNone(index_summary([])['nloc_weighted_mean'])

    @unittest.skipIf(lizard is None, 'requires scripts/requirements-maintainability.txt')
    def test_halstead_hand_counts_and_comments(self):
        h = halstead('R/a.R', 'x <- x + 1', 'R')
        self.assertEqual((h['distinct_operators'], h['distinct_operands'],
                          h['operators'], h['operands'], h['volume']), (2, 2, 2, 3, 10))
        self.assertEqual(h, halstead('R/a.R', '# x + 1\nx <- x + 1 # more', 'R'))
        h = halstead('src/a.cpp', 'int x = x + 1;', 'C++')
        self.assertEqual((h['distinct_operators'], h['distinct_operands'],
                          h['operators'], h['operands']), (4, 2, 4, 3))
        self.assertAlmostEqual(h['volume'], 7 * math.log2(6))
        self.assertEqual(h, halstead('src/a.cpp', '#include <a>\n/* x */ int x = x + 1; // c', 'C++'))
        self.assertEqual(halstead('R/a.R', 'x <<- 1', 'R')['operators'], 1)
        self.assertEqual(halstead('src/a.cpp', 'x >>= 1;', 'C++')['operators'], 2)
        self.assertEqual(halstead('R/a.R', '"# string"', 'R')['operands'], 1)

    @unittest.skipIf(lizard is None, 'requires scripts/requirements-maintainability.txt')
    def test_scored_files_and_legacy_json(self):
        result = analyze([('R/empty.R', '# comment'),
                          ('R/a.R', 'f <- function(x) { if (x) 1 else 2 }')])
        self.assertEqual(result['index']['measured_files'], 1)
        self.assertEqual(result['index']['total_files'], 2)
        files = result['languages']['R']['file_metrics']
        self.assertEqual(files[0]['complexity'], 2)
        self.assertIsNone(files[1]['mi'])
        with tempfile.TemporaryDirectory() as directory:
            p = Path(directory) / 'old.json'
            result.pop('index')
            for value in result['languages'].values():
                value.pop('index'); value.pop('file_metrics')
            p.write_text(json.dumps(dict(result, ref='old')))
            rendered = report([p])
            self.assertIn('| old | Overall | Not measured |', rendered)
            p.write_text(json.dumps(dict(ref='missing', status='unavailable', languages={})))
            self.assertIn('| missing | Overall | Not measured |', report([p]))

    def test_ranking_sensitivity_is_explicit(self):
        data = [dict(ref='a', index=dict(nloc_weighted_mean=20, file_mean=30)),
                dict(ref='b', index=dict(nloc_weighted_mean=19.9, file_mean=40)),
                dict(ref='unavailable')]
        text = '\n'.join(index_interpretation(data))
        self.assertIn('`a` has the highest NLOC-weighted', text)
        self.assertIn('by 0.10 points', text)
        self.assertIn('`b` has the highest equal-file mean', text)
        self.assertIn('does **not** establish a robust', text)
        self.assertEqual(index_interpretation([data[2]]), [])

    def test_matched_comparison_fixed_weights(self):
        def result(ref, files):
            return dict(ref=ref, languages={'R': {'file_metrics': files}})
        baseline = result('base', [dict(path='a', mi=20, nloc=90), dict(path='b', mi=60, nloc=10)])
        branch = result('new', [dict(path='a', mi=30, nloc=10), dict(path='b', mi=40, nloc=90),
                                dict(path='c', mi=100, nloc=1)])
        rendered = '\n'.join(comparison_details([baseline, branch]))
        self.assertIn('Shared paths: 2; added: 1; removed: 0.', rendered)
        self.assertIn('fixed baseline NLOC weights): 7.00', rendered)


if __name__ == '__main__':
    unittest.main()
